M48
; DRILL file {KiCad (6.0.6)} date Fri Apr  7 17:46:21 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-07T17:46:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.0236
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X5.66Y-3.56
X5.87Y-3.56
T2
X5.66Y-3.5
X5.73Y-3.36
X6.01Y-3.15
X6.08Y-3.36
T3
X5.1Y-3.149
X5.1Y-3.249
X5.1Y-3.349
X5.1Y-3.449
X6.2Y-3.1
X6.2Y-3.2
X6.2Y-3.5
X6.3Y-3.6
X6.35Y-3.1
X6.35Y-3.2
X6.4Y-3.5
T0
M30
